@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Books
# @name Books_GET
GET {{server}}/admin/Books
{{auth}}


### Books
# @name Books_POST
POST {{server}}/odata/v4/admin/Books
Content-Type: application/json
{{auth}}

{
  "ID": 3345241,
  "title": "title-3345241",
  "author": {
    "ID": 11375660
  },
  "descr": "descr-3345241",
  "stock": 74,
  "createdAt": "2005-12-03T22:00:00.000Z",
  "createdBy": "createdBy.1zp7d@example.org",
  "modifiedAt": "2009-04-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.1zp7d@example.net",
  "price": 5.23,
  "genre": {
    "ID": 7710727
  },
  "owner": "owner-3345241"
}


### Books
# @name Books_PATCH
PATCH {{server}}/odata/v4/admin/Books/3345241
Content-Type: application/json
{{auth}}

{
  "ID": 3345241,
  "title": "title-3345241",
  "author": {
    "ID": 11375660
  },
  "descr": "descr-3345241",
  "stock": 74,
  "createdAt": "2005-12-03T22:00:00.000Z",
  "createdBy": "createdBy.1zp7d@example.org",
  "modifiedAt": "2009-04-13T22:00:00.000Z",
  "modifiedBy": "modifiedBy.1zp7d@example.net",
  "price": 5.23,
  "genre": {
    "ID": 7710727
  },
  "owner": "owner-3345241"
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/admin/Books/3345241
Content-Type: application/json
{{auth}}


### Authors
# @name Authors_GET
GET {{server}}/odata/v4/admin/Authors
{{auth}}


### Authors
# @name Authors_POST
POST {{server}}/odata/v4/admin/Authors
Content-Type: application/json
{{auth}}

{
  "ID": 11375660,
  "name": "name-11375660",
  "dateOfBirth": "2020-06-05",
  "dateOfDeath": "2006-06-12",
  "placeOfBirth": "placeOfBirth-11375660",
  "placeOfDeath": "placeOfDeath-11375660",
  "createdAt": "2003-11-22T22:00:00.000Z",
  "createdBy": "createdBy.6rtik@example.net",
  "modifiedAt": "2006-10-02T22:00:00.000Z",
  "modifiedBy": "modifiedBy.6rtik@example.net"
}


### Authors
# @name Authors_PATCH
PATCH {{server}}/odata/v4/admin/Authors/11375660
Content-Type: application/json
{{auth}}

{
  "ID": 11375660,
  "name": "name-11375660",
  "dateOfBirth": "2020-06-05",
  "dateOfDeath": "2006-06-12",
  "placeOfBirth": "placeOfBirth-11375660",
  "placeOfDeath": "placeOfDeath-11375660",
  "createdAt": "2003-11-22T22:00:00.000Z",
  "createdBy": "createdBy.6rtik@example.net",
  "modifiedAt": "2006-10-02T22:00:00.000Z",
  "modifiedBy": "modifiedBy.6rtik@example.net"
}


### Authors
# @name Authors_DELETE
DELETE {{server}}/odata/v4/admin/Authors/11375660
Content-Type: application/json
{{auth}}


### MyBooks
# @name MyBooks_GET
GET {{server}}/odata/v4/admin/MyBooks
{{auth}}


### MyBooks
# @name MyBooks_POST
POST {{server}}/odata/v4/admin/MyBooks
Content-Type: application/json
{{auth}}

{
  "ID": 27907567,
  "price": 32.11,
  "owner": "owner-27907567",
  "genre": {
    "ID": 7710727
  }
}


### MyBooks
# @name MyBooks_PATCH
PATCH {{server}}/odata/v4/admin/MyBooks/27907567
Content-Type: application/json
{{auth}}

{
  "ID": 27907567,
  "price": 32.11,
  "owner": "owner-27907567",
  "genre": {
    "ID": 7710727
  }
}


### MyBooks
# @name MyBooks_DELETE
DELETE {{server}}/odata/v4/admin/MyBooks/27907567
Content-Type: application/json
{{auth}}


### Genres
# @name Genres_GET
GET {{server}}/odata/v4/admin/Genres
{{auth}}


### Genres
# @name Genres_POST
POST {{server}}/odata/v4/admin/Genres
Content-Type: application/json
{{auth}}

{
  "ID": 7710727,
  "name": "name-7710727",
  "parent": {
    "ID": 7710727
  }
}


### Genres
# @name Genres_PATCH
PATCH {{server}}/odata/v4/admin/Genres/7710727
Content-Type: application/json
{{auth}}

{
  "ID": 7710727,
  "name": "name-7710727",
  "parent": {
    "ID": 7710727
  }
}


### Genres
# @name Genres_DELETE
DELETE {{server}}/odata/v4/admin/Genres/7710727
Content-Type: application/json
{{auth}}
