@server = http://localhost:4004
@auth = Authorization: Basic alice:


### ListOfBooks
# @name ListOfBooks_GET
GET {{server}}/odata/v4/catalog/ListOfBooks
{{auth}}


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books
{{auth}}


### MyBooks
# @name MyBooks_GET
GET {{server}}/odata/v4/catalog/MyBooks
{{auth}}


### Genres
# @name Genres_GET
GET {{server}}/odata/v4/catalog/Genres
{{auth}}


### Genres
# @name Genres_POST
POST {{server}}/odata/v4/catalog/Genres
Content-Type: application/json
{{auth}}

{
  "ID": 22059107,
  "name": "name-22059107",
  "parent": {
    "ID": 22059107
  }
}


### Genres
# @name Genres_PATCH
PATCH {{server}}/odata/v4/catalog/Genres/22059107
Content-Type: application/json
{{auth}}

{
  "ID": 22059107,
  "name": "name-22059107",
  "parent": {
    "ID": 22059107
  }
}


### Genres
# @name Genres_DELETE
DELETE {{server}}/odata/v4/catalog/Genres/22059107
Content-Type: application/json
{{auth}}


### submitOrder
# @name submitOrder_POST
POST {{server}}/odata/v4/catalog/submitOrder
Content-Type: application/json
{{auth}}

{
  "book": 4615287,
  "quantity": 0
}
